### ISSUE TITLE
Falliatcom

### ISSUE THREAD

**Issue by Falliatcom17** [twitterdev/account-activity-dashboard#21]
We would like to authenticate the @falliatcom account with the verification badge, the blue flag of our Twitter account

**Comment by andypiper** [comment]
What is the question or issue here please?

**Comment by Falliatcom17** [comment]
We would like to authenticate the @falliatcom account with the verification badge, the blue flag of our Twitter account

**Comment by andypiper** [comment]
This is the code for a Twitter API sample, we are unable to help you with that question here.
