### ISSUE TITLE
Verified

### ISSUE THREAD

**Issue by alharbi20** [twitterdev/account-activity-dashboard#30]

**Comment by andypiper** [comment]
This repository contains code for the account activity API dashboard sample app. What issue are you reporting?

**Comment by alharbi20** [comment]
I need to verify my account

**Comment by andypiper** [comment]
You will need to use [this page](https://help.twitter.com/en/managing-your-account/about-twitter-verified-accounts) for help. This repository is for Twitter API sample code.

Closing as off-topic / invalid.
