### ISSUE TITLE
Can't create webhook

### ISSUE THREAD

**Issue by JordanVScher** [twitterdev/account-activity-dashboard#4]
Hi. I've been trying to run this example but I can't create an webhook. I added Account Activity to my app permissions and changed the webhook_env to dev. I'm using ngrok. Let's say I have the following webhook url: `https://213a8156.ngrok.io` and I added the two following callbacks url on settings: `https://213a8156.ngrok.io/callbacks/addsub` `https://213a8156.ngrok.io/callbacks/removesub`. (I don't know the parenthesis in http(s) mean)

When I run: `node example_scripts/webhook_management/create-webhook-config.js -e dev -u https://213a8156.ngrok.io` all I get back is a Forbidden message with code 200. The web UI says 'Webhook config unable to be retrieved'. 

Anyone knows what I'm doing wrong?

**Comment by andypiper** [comment]
Since you closed this out I assume you resolved it yourself, are you able to share the resolution to help others? Thanks!

**Comment by JordanVScher** [comment]
Hi. What happened is that I got somewhat confused with the "env" var. It didn't occur to me that it was the same env i had set up when I got access to the Activity Account API. I think the tutorial could be clearer on this matter by linking the user to https://developer.twitter.com/en/apply and explaining how the beta access and the whole env thing works a little better.

**Comment by vikasparth** [comment]
In my case, also I found out that I had given wrong environment name, I had to give environment name for Account Activity APISandbox environment
