### ISSUE TITLE
Live Activity is not showing anything

### ISSUE THREAD

**Issue by rraallvv** [twitterdev/account-activity-dashboard#9]
Any particular reason why the Live Activity tap shows only a message saying Waiting for activity and not showing anything else?

I had to apply path #6 to be able to use it with ngrok, then the web page asked me to authorize authorized the app, and I did so, I not sure why is that even needed if I've already put the account's TWITTER_ACCESS_TOKEN and TWITTER_ACCESS_TOKEN_SECRET in the configuration file.

By the way, the TWITTER_ACCESS_TOKEN and TWITTER_ACCESS_TOKEN_SECRET I'm using are not those for the twitter developer account but those for the Twitter account that I want to see the live activity, is that correct?

**Comment by andypiper** [comment]
The Live Activity tab relies on web sockets between the local node server that is receiving data from the API, and the open browser window. So, it will only show responses as they arrive in real time while the tab is open. If you switch tabs, the websocket will be reset and existing activity will vanish (but will still show in the console where your node server is running.

The access token and secret in the configuration file are for the app to register the webhook and subscriptions. They are not used to receive activities. When the app is started, there will be no registered webhook, and no subscriptions. You have to first register the webhook in the UI, and then once this is set up, you add subscriptions for individual accounts via sign-in with Twitter on the subscriptions tab. Then, activities related to those subscriptions can start to flow through.

**Comment by rraallvv** [comment]
Thanks for looking into this. I think I was able to run the demo, at last. I'm not sure what was the problem though, maybe I was using the wrong access tokens.
